name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Backend Job
  backend:
    name: Build and Push Backend to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t mqzcn/trivia_java:latest -f ./trivia_api/Dockerfile ./trivia_api
          docker push mqzcn/trivia_java:latest

  # Frontend Job
  frontend:
    name: Build and Push Frontend to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t mqzcn/trivia_react:latest -f ./trivia_frontend/Dockerfile ./trivia_frontend
          docker push mqzcn/trivia_react:latest
